FROM node:lts-alpine

WORKDIR /home/node/server

#ENV NODE_ENV=dev

RUN apk add --no-cache bash

COPY package*.json ./
COPY tsconfig*.json ./
# COPY tsconfig*.json ./

RUN npm install

# RUN npm install pm2 -g

#RUN npm run build

#COPY dist .

#EXPOSE 3300

# CMD ["pm2-runtime","app.js"]
